### ISSUE TITLE
Cannot follow link from README

### ISSUE THREAD

**Issue by epogrebnyak** [SlipperyBrick/blocks#3]
Very useful addition to mdbook, thanks for setting up!

https://slipperybrick.github.io/Blocks/components/components-introduction.html lisnk from README does not render though.

**Comment by SlipperyBrick** [comment]
Thanks for catching this. Just updated the README to the correct link. I'm still in the process of writing the documentation so there is a lot on there that is unfinished, but the links to what keys each component requires, as well as usage is documented enough to start using the components available in the Blocks component library. I'll be adding more and fixing up a few things in the coming months :)
